### ISSUE TITLE
Add Bootstrap

### ISSUE THREAD

**Issue by mallenswe** [mallenswe/Hacktoberfest2021#1]
We want to use bootstrap to style the website and make development quicker. Add Bootstrap to the index.html file by following these guidelines: [bootstrap](https://getbootstrap.com/docs/5.1/getting-started/introduction/)

**Comment by ahmed120993** [comment]
1- Is it possible to apply for a paid job?  2- I know Turkish, Arabic and a little English 3- If you need a large social support mechanism, the matter concerns you 4- I wish you progress.  5- I hope to accept the job
